export const IGNORED_ASSESSMENTS = [
  "TaxonomyTextLengthAssessment",
  "UrlLengthAssessment",
  "UrlStopWordsAssessment",
  // Produces incorrect results; replaced by custom assessment
  "SingleH1Assessment",
];

export const ASSESSMENT_CONFIG_LOOKUP = {
  FleschReadingEaseAssessment: "fleschReading",
  SentenceLengthInTextAssessment: "sentenceLength",
};

export const KEYPHRASE_ASSESSMENTS = [
  "FunctionWordsInKeyphraseAssessment",
  "IntroductionKeywordAssessment",
  "KeyphraseLengthAssessment",
  "KeywordDensityAssessment",
  // "KeywordStopWordsAssessment",
  "KeyphraseDistributionAssessment",
  "MetaDescriptionKeywordAssessment",
  "SubheadingsKeywordAssessment",
  "TitleKeywordAssessment",
  "UrlKeywordAssessment",
];

// See: https://yoast.com/help/features-per-language/
export const SUPPORTED_ASSESSMENTS_PER_LOCALE = {
  WordComplexityAssessment: ["de", "en", "es", "fr"],
  KeyphraseDistributionAssessment: [
    "ar",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "fr",
    "he",
    "hu",
    "id",
    "it",
    "ja",
    "nl",
    "no",
    "pl",
    "pt",
    "ru",
    "sk",
    "sv",
    "tr",
  ],
  SentenceLengthInDescriptionAssessment: [
    "ar",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "fa",
    "fr",
    "he",
    "hu",
    "id",
    "it",
    "ja",
    "nl",
    "no",
    "pl",
    "pt",
    "ru",
    "sk",
    "sv",
    "tr",
  ],
  SentenceLengthInTextAssessment: [
    "ar",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "fa",
    "fr",
    "he",
    "hu",
    "id",
    "it",
    "ja",
    "nl",
    "no",
    "pl",
    "pt",
    "ru",
    "sk",
    "sv",
    "tr",
  ],
  PassiveVoiceAssessment: [
    "ar",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "fa",
    "fr",
    "he",
    "hu",
    "id",
    "it",
    "nl",
    "no",
    "pl",
    "pt",
    "ru",
    "sk",
    "sv",
    "tr",
  ],
  TransitionWordsAssessment: [
    "ar",
    "ca",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "fa",
    "fr",
    "he",
    "hu",
    "id",
    "it",
    "nl",
    "no",
    "pl",
    "pt",
    "ru",
    "sk",
    "sv",
    "tr",
  ],
  FunctionWordsInKeyphraseAssessment: [
    "ar",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "fa",
    "fr",
    "he",
    "hu",
    "id",
    "it",
    "ja",
    "nl",
    "no",
    "pl",
    "pt",
    "ru",
    "sk",
    "sv",
    "tr",
  ],
  FleschReadingEaseAssessment: ["de", "en", "es", "fr", "it", "nl", "pt", "ru"],
  // TODO: Synonyms, related keyphrases and word forms
  // SynonymsRelatedKeyphrasesWordFormsAssessment: [
  //   "ar",
  //   "cs",
  //   "de",
  //   "el",
  //   "en",
  //   "es",
  //   "fr",
  //   "he",
  //   "hu",
  //   "id",
  //   "it",
  //   "ja",
  //   "nl",
  //   "no",
  //   "pl",
  //   "pt",
  //   "ru",
  //   "sk",
  //   "sv",
  //   "tr",
  // ],
};

export const LANG_CULTURES = Object.freeze({
  af: "af-ZA",
  ar: "ar-SA",
  az: "az-Latn-AZ",
  be: "be-BY",
  bg: "bg-BG",
  ca: "ca-ES",
  cs: "cs-CZ",
  da: "da-DK",
  de: "de-DE",
  dv: "dv-MV",
  el: "el-GR",
  en: "en-US",
  es: "es-ES",
  et: "et-EE",
  eu: "eu-ES",
  fa: "fa-IR",
  fi: "fi-FI",
  fo: "fo-FO",
  fr: "fr-FR",
  gl: "gl-ES",
  gu: "gu-IN",
  he: "he-IL",
  hi: "hi-IN",
  hr: "hr-HR",
  hu: "hu-HU",
  hy: "hy-AM",
  id: "id-ID",
  is: "is-IS",
  it: "it-IT",
  ja: "ja-JP",
  ka: "ka-GE",
  kk: "kk-KZ",
  kn: "kn-IN",
  ko: "ko-KR",
  kok: "kok-IN",
  ky: "ky-KG",
  lt: "lt-LT",
  lv: "lv-LV",
  mk: "mk-MK",
  mn: "mn-MN",
  mr: "mr-IN",
  ms: "ms-MY",
  nl: "nl-NL",
  no: "nb-NO",
  pa: "pa-IN",
  pl: "pl-PL",
  pt: "pt-BR",
  ro: "ro-RO",
  ru: "ru-RU",
  sa: "sa-IN",
  sk: "sk-SK",
  sl: "sl-SI",
  sq: "sq-AL",
  sr: "sr-Latn-CS",
  sv: "sv-SE",
  sw: "sw-KE",
  syr: "syr-SY",
  ta: "ta-IN",
  te: "te-IN",
  th: "th-TH",
  tr: "tr-TR",
  tt: "tt-RU",
  uk: "uk-UA",
  ur: "ur-PK",
  uz: "uz-Latn-UZ",
  vi: "vi-VN",
});
