title: Playground

buttons:
  seo-audit:
    keyphraseField: metakeyphrase
    synonymsField: metasynonyms
    logLevel: debug
  social:
    icon: cart
    text: Buy
    link: https://kirby.tools/seo-audit/buy
    theme: love-icon

columns:
  - width: 1/2
    sections:
      seoAudit:
        type: seo-audit
        keyphraseField: metakeyphrase
        synonymsField: metasynonyms
        logLevel: debug
  - width: 1/2
    sections:
      configuration:
        type: fields
        fields:
          gettingStartedInfo:
            type: info
            label: Getting Started
            text: |
              Enter the URL of a page you would like to analyze. The report will be generated based on the content of the page and provide you with a list of SEO recommendations. In your projects, the plugin will use the URL of the current page and read the configuration from the blueprint.
            theme: passive
          targetUrl:
            label: URL to Analyze
            type: url
            help: Will be the current page in the production version.
          assessments:
            label: Assessments
            type: multiselect
            options:
              # Plugin assessments
              singleH1: Single H1
              headingStructureOrder: Heading Structure Order
              altAttribute: Alt Attribute
              # Yoast SEO assessments
              introductionKeyword: Introduction Keyword
              keyphraseLength: Keyphrase Length
              keyphraseDensity: Keyword Density
              metaDescriptionKeyword: Meta Description Keyword
              metaDescriptionLength: Meta Description Length
              subheadingsKeyword: Subheadings Keyword
              textCompetingLinks: Text Competing Links
              imageKeyphrase: Image Keyphrase
              images: Text Images
              textLength: Text Length
              externalLinks: Outbound Links
              keyphraseInSEOTitle: Title Keyword
              internalLinks: Internal Links
              titleWidth: Page Title Width
              slugKeyword: Url Keyword
              functionWordsInKeyphrase: Function Words in Keyphrase
              keyphraseDistribution: Keyphrase Distribution
              subheadingsTooLong: Subheading Distribution Too Long
              textParagraphTooLong: Paragraph Too Long
              textSentenceLength: Sentence Length in Text
              textTransitionWords: Transition Words
              passiveVoice: Passive Voice
              textPresence: Text Presence
              sentenceBeginnings: Sentence Beginnings
              wordComplexity: Word Complexity
            help: By default, all assessments are included. Customize the report to your needs.
          language:
            label: Language
            type: select
            required: true
            options:
              de: German
              en: English
              es: Spanish
              fr: French
              nl: Dutch
            help: Will use the user's Panel language in the production version.
            width: 1/2
          links:
            label: Recommendation Links?
            type: toggle
            width: 1/2
          lineFields:
            type: line
          fieldsInfo:
            type: info
            label: Fields
            text: |
              The following fields add further context for the SEO analysis. They are not required but can help to improve the report.
            theme: passive
          metaKeyphrase:
            label: Focus Keyphrase
            type: text
            help: Enter the keyword or keyphrase you want the page to rank for in Google. Next, analyze the content of the page to see if search engines understand what it is about.
          metaSynonyms:
            label: Keyphrase Synonyms
            type: tags
            help: Using synonyms is a way to help users understand your copy better, and search engines will recognize these synonyms as well.
          lineBlueprintCode:
            type: line
      blueprintCode:
        label: Blueprint Generator
        type: playground-blueprint-code
        help: This is the section code with all the configuration options you have currently selected. Copy and paste this code into your blueprint of choice.
